USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS OUTBREAK_DB;
CREATE SCHEMA IF NOT EXISTS OUTBREAK_DB.EARLY_WARNING;

-- shared role for your team
CREATE ROLE IF NOT EXISTS HACK_TEAM;
GRANT USAGE ON DATABASE OUTBREAK_DB TO ROLE HACK_TEAM;
GRANT ALL ON SCHEMA OUTBREAK_DB.EARLY_WARNING TO ROLE HACK_TEAM;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE HACK_TEAM;
GRANT ROLE HACK_TEAM TO ROLE ACCOUNTADMIN;

USE ROLE ACCOUNTADMIN;
GRANT ROLE HACK_TEAM TO ROLE SYSADMIN;

USE ROLE ACCOUNTADMIN;

-- 1. Who exists in the account (your 3 teammates should be listed once they've accepted)
SHOW USERS;

-- 2. Who has HACK_TEAM directly
SHOW GRANTS OF ROLE HACK_TEAM;

-- 3. Who has SYSADMIN (these people get HACK_TEAM's access through it)
SHOW GRANTS OF ROLE SYSADMIN;

SHOW USERS LIKE 'KULSUMMOHAMAD15';

ALTER USER KULSUMMOHAMAD15 SET DEFAULT_ROLE = SYSADMIN;

SELECT CURRENT_ROLE(), CURRENT_ACCOUNT();