USE ROLE HACK_TEAM;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE OUTBREAK_DB;
USE SCHEMA OUTBREAK_DB.EARLY_WARNING;

-- Train on everything except the last 2 years; detect anomalies in the last 2 years
CREATE OR REPLACE VIEW STATE_ANOM_TRAIN_V AS
SELECT CITY AS SERIES, WEEK_START::TIMESTAMP_NTZ AS TS, CASES::FLOAT AS Y
FROM STATE_WEEKLY
WHERE WEEK_START < (SELECT DATEADD(week, -104, MAX(WEEK_START)) FROM STATE_WEEKLY);

CREATE OR REPLACE VIEW STATE_ANOM_TEST_V AS
SELECT CITY AS SERIES, WEEK_START::TIMESTAMP_NTZ AS TS, CASES::FLOAT AS Y
FROM STATE_WEEKLY
WHERE WEEK_START >= (SELECT DATEADD(week, -104, MAX(WEEK_START)) FROM STATE_WEEKLY);

CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION STATE_ANOMALY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'STATE_ANOM_TRAIN_V'),
  SERIES_COLNAME => 'SERIES',
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CALL STATE_ANOMALY_MODEL!DETECT_ANOMALIES(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'STATE_ANOM_TEST_V'),
  SERIES_COLNAME => 'SERIES',
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'Y',
  CONFIG_OBJECT => {'prediction_interval': 0.99}
);

CREATE OR REPLACE TABLE ANOMALY_RESULTS AS
SELECT SERIES::STRING AS CITY, TS::DATE AS WEEK_START, Y AS CASES,
       FORECAST AS EXPECTED, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- Forecast the next 8 weeks from all history
CREATE OR REPLACE VIEW STATE_FC_TRAIN_V AS
SELECT CITY AS SERIES, WEEK_START::TIMESTAMP_NTZ AS TS, CASES::FLOAT AS Y
FROM STATE_WEEKLY;

CREATE OR REPLACE SNOWFLAKE.ML.FORECAST STATE_FORECAST_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'STATE_FC_TRAIN_V'),
  SERIES_COLNAME => 'SERIES',
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'Y'
);

CALL STATE_FORECAST_MODEL!FORECAST(
  FORECASTING_PERIODS => 8,
  CONFIG_OBJECT => {'prediction_interval': 0.9}
);

CREATE OR REPLACE TABLE FORECAST_RESULTS AS
SELECT SERIES::STRING AS CITY, TS::DATE AS WEEK_START, FORECAST, LOWER_BOUND, UPPER_BOUND
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- Alert list: anomalies above the upper bound, with a simple severity label
CREATE OR REPLACE VIEW STATE_ALERTS AS
SELECT CITY, WEEK_START, CASES, ROUND(EXPECTED) AS EXPECTED, ROUND(UPPER_BOUND) AS UPPER_BOUND,
       ROUND(CASES - UPPER_BOUND) AS OVER_BOUND,
       CASE WHEN CASES > 3 * UPPER_BOUND THEN 'Critical'
            WHEN CASES > 1.5 * UPPER_BOUND THEN 'Warning'
            ELSE 'Watch' END AS SEVERITY
FROM ANOMALY_RESULTS
WHERE IS_ANOMALY AND CASES > UPPER_BOUND AND CASES >= 20;

-- Sanity check
SELECT CITY, COUNT(*) AS weeks, SUM(IFF(IS_ANOMALY, 1, 0)) AS anomalies
FROM ANOMALY_RESULTS GROUP BY CITY ORDER BY anomalies DESC;OUTBREAK_DB.EARLY_WARNING.RAW_STAGE

-- View the future forecast for all cities
SELECT * 
FROM FORECAST_RESULTS 
ORDER BY WEEK_START ASC, CITY ASC;

-- 1. Create a cleaned training view that turns NULLs into 0
CREATE OR REPLACE VIEW STATE_FC_TRAIN_CLEAN_V AS
SELECT 
    CITY AS SERIES, 
    WEEK_START::TIMESTAMP_NTZ AS TS, 
    COALESCE(CASES, 0)::FLOAT AS Y -- Fixes the NULL bug by treating missing weeks as 0 cases
FROM STATE_WEEKLY;

-- 2. Retrain the model on the clean data
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST STATE_FORECAST_MODEL_V2(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'STATE_FC_TRAIN_CLEAN_V'),
  SERIES_COLNAME => 'SERIES',
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'Y'
);

-- 3. Run the forecast 
CALL STATE_FORECAST_MODEL_V2!FORECAST(
  FORECASTING_PERIODS => 8,
  CONFIG_OBJECT => {'prediction_interval': 0.9}
);

-- 4. Overwrite your results table and force a mathematical floor of 0
CREATE OR REPLACE TABLE FORECAST_RESULTS AS
SELECT 
    SERIES::STRING AS CITY, 
    TS::DATE AS WEEK_START, 
    GREATEST(0, ROUND(FORECAST)) AS FORECAST,      -- Force negative predictions to 0
    GREATEST(0, ROUND(LOWER_BOUND)) AS LOWER_BOUND, -- Fixes negative safety ranges
    GREATEST(0, ROUND(UPPER_BOUND)) AS UPPER_BOUND
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
